---
title: "PCA and Clustering"
author: "Cristina Gonzales"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(here)
library(ggrepel)
library(gganimate)
library(ggplot2)
```

New stuff: PCA and clustering (k-means and hierarchal)

```{r}
all <- read_csv(here("data/all.csv")) 

#only keeping numeric var for pca
all_pca <- all %>%
  select(danceability, energy, loudness, speechiness, acousticness, instrumentalness,
         liveness, valence, tempo, duration_ms, time_signature)

all_cluster <- all %>%
  select(danceability, energy, loudness, speechiness, acousticness, instrumentalness,
         liveness, valence, tempo, duration_ms, mode, time_signature, explicit)
```

```{r}
#PCA
pr.out = prcomp(all_pca, scale = TRUE)

#means
pr.out$center
#standard dev
pr.out$scale
#principal component loading
pr.out$rotation

#biplot
pr.out$rotation = - pr.out$rotation
pr.out$x = - pr.out$x
biplot(pr.out, scale = 0)

#variance of principal components
pr.var = pr.out$sdev^2
pve = pr.var / sum(pr.var)

#principal comp vs var plots
plot(pve, xlab = "Principal Component", ylab = "Proportion of Variance Explained",
     ylim = c(0, 1), type = "b")
plot(cumsum(pve), xlab = "Princple Component", ylab = "Cumulative Proportion of Variance Explained",
     ylim = c(0, 1), type = "b")
```

```{r}
#k means with k = 7
km.out = kmeans(all_cluster, centers = 7, nstart = 50)
plot(all_cluster, col = (km.out$cluster + 1), main = "K-means Clustering Results With K=7",
     pch = 20, cex = 2)

#k means with k = 8
km.out1 = kmeans(all_cluster, centers = 8, nstart = 50)
plot(all_cluster, col = (km.out1$cluster + 1), main = "K-means Clustering Results With K=7",
     pch = 20, cex = 2)
```

```{r}
#clustering with albums, not individual songs
album_pca <- all %>%
  group_by(album_name) %>%
  summarize(danceability = mean(danceability),
         energy = mean(energy),
         loudness = mean(loudness), 
         speechiness = mean(speechiness), 
         acousticness = mean(acousticness), 
         instrumentalness = mean(instrumentalness),
         liveness = mean(liveness), 
         valence = mean(valence), 
         tempo = mean(tempo), 
         duration_ms = mean(duration_ms), 
         time_signature = mean(time_signature)) %>%
  select(-album_name)

album_PCA_titles <- all %>%
  group_by(album_name) %>%
  summarize(danceability = mean(danceability),
         energy = mean(energy),
         loudness = mean(loudness), 
         speechiness = mean(speechiness), 
         acousticness = mean(acousticness), 
         instrumentalness = mean(instrumentalness),
         liveness = mean(liveness), 
         valence = mean(valence), 
         tempo = mean(tempo), 
         duration_ms = mean(duration_ms), 
         time_signature = mean(time_signature)) %>%
  mutate(artist = case_when(
    album_name %in% c("Taylor Swift", "Fearless", "Speak Now", "Red", "1989",
                      "reputation", "Lover", "folklore", "evermore") ~ "Taylor Swift",
    album_name %in% c("Yours Truly", "My Everything", "Dangerous Woman", "thank u, next",
                      "Sweetener", "Positions") ~ "Ariana Grande",
    album_name %in% c("Yellow Submarine Songtrack", "Live At The Hollywood Bowl", 
                      "The Beatles") ~ "The Beatles",
    album_name == "Honeymoon" ~ "Beach Bunny",
    album_name %in% c("True Romance", "SUCKER", "Number 1 Angel", "Pop 2",
                      "Charli", "how i'm feeling now") ~ "Charli XCX",
    album_name %in% c("Wide Open Spaces", "Fly", "Home", "Taking The Long Way",
                      "Gaslighter") ~ "The Chicks",
    album_name %in% c("Tug of War", "Kiss", "Emotion", "EMOTION SIDE B +", "Dedicated",
                      "Dedicated Side B") ~ "Carly Rae Jepsen",
    album_name %in% c("So Far Gone", "Thank Me Later", "Take Care", "Nothing Was The Same",
                      "If You're Reading This It's Too Late", "What A Time To Be Alive", "Views",
                      "More Life", "Scorpion", "Care Package", "Dark Lane Demo Tapes") ~ "Drake",
    album_name %in% c("Dua Lipa", "Future Nostalgia") ~ "Dua Lipa",
    album_name %in% c("Wasteland, Baby!", "Hozier") ~ "Hozier",
    album_name %in% c("For Emma, Forever Ago", "Bon Iver", "22, A Million", "i,i") ~ "Bon Iver",
    album_name %in% c("The College Dropout", "Late Registration", "Graduation", "808s & Heartbreak",
                      "My Beautiful Dark Twisted Fantasy", "Watch The Throne", "Yeezus",
                      "The Life Of Pablo", "ye", "KIDS SEE GHOSTS", "JESUS IS KING") ~ "Kanye",
    album_name %in% c("Pure Heroine", "Melodrama") ~ "Lorde",
    album_name %in% c("Wednesday Morning, 3 A.M.", "Parsley, Sage, Rosemary And Thyme", "Bookends",
                      "The Graduate", "Bridge Over Troubled Water") ~ "Simon & Garfunkel"
    
  ))

```

```{r}
#pca with albums
pr.out_album = prcomp(album_pca, scale = TRUE)

#means
pr.out_album$center
#standard dev
pr.out_album$scale
#principal component loading
pr.out_album$rotation

#biplot
pr.out_album$rotation = - pr.out_album$rotation
pr.out_album$x = - pr.out_album$x
biplot(pr.out_album, scale = 0)

#variance of principal components
pr.var_album = pr.out_album$sdev^2
pve_album = pr.var_album / sum(pr.var_album)

#principal comp vs var plots
plot(pve_album, xlab = "Principal Component", ylab = "Proportion of Variance Explained",
     ylim = c(0, 1), type = "b")
plot(cumsum(pve_album), xlab = "Princple Component", ylab = "Cumulative Proportion of Variance Explained",
     ylim = c(0, 1), type = "b")

#pca graphs
pca_rotations <- data.frame(pr.out_album$rotation)
pca_rotations$variables <- rownames(pca_rotations)
PC1graph <- 
  ggplot(data = pca_rotations, mapping = aes(x = variables, y = PC1, 
                                          fill = variables)) +
  geom_col() +
  coord_flip() +
  labs(title = "Production: Simple vs. Embellished") +
  theme(legend.position = "none")
PC1graph

PC2graph <- 
  ggplot(data = pca_rotations, mapping = aes(x = variables, y = PC2, 
                                          fill = variables)) +
  geom_col() +
  coord_flip() +
  theme(legend.position = "none") +
  labs(title = "Rhythm vs. Energy")
PC2graph

PC3graph <- 
  ggplot(data = pca_rotations, mapping = aes(x = variables, y = PC3, 
                                          fill = variables)) +
  geom_col() +
  coord_flip() +
  theme(legend.position = "none")
PC3graph

pca_titles <- as.data.frame(pr.out_album$x)
pca_titles$album_name <- album_PCA_titles$album_name
pca_titles$artist <- album_PCA_titles$artist

taylor_pca <- ggplot(pca_titles, aes(x = PC1, y = PC2)) +
  geom_point(alpha = .3) +
  geom_text_repel(data = subset(pca_titles, artist == "Taylor Swift"),
            aes(label = album_name)) +
  geom_point(data = subset(pca_titles, artist == "Taylor Swift"), 
             mapping = aes(x = PC1, y = PC2),
             alpha = .7, color = "purple2") +
  ylab("Rhythm vs. Energy") +
  xlab("Production: Simple vs Embellished")
taylor_pca

p_pca_album <- ggplot(pca_titles, aes(x = PC1, y = PC2)) +
  geom_text(data = pca_titles, aes(label = album_name, y = PC2 + .2)) +
  xlab("Production: Simple vs Embellished") +
  ylab("Rhythm vs Energy") +
  transition_states(artist, transition_length = 5)
animate(p_pca_album, fps = 0.5) + 
  ggtitle('Artist: {closest_state}')
```

```{r}
##clustering with albums
#choosing k
n_pca <- as_tibble(pr.out_album$x[, 1:3])
n_clusters_kmeans1<-kmeans(n_pca, centers = 1, nstart = 20)
n_clusters_kmeans2<-kmeans(n_pca, centers = 2, nstart = 20)
n_clusters_kmeans3<-kmeans(n_pca, centers = 3, nstart = 20)
n_clusters_kmeans4<-kmeans(n_pca, centers = 4, nstart = 20)
n_clusters_kmeans5<-kmeans(n_pca, centers = 5, nstart = 20)
n_clusters_kmeans6<-kmeans(n_pca, centers = 6, nstart = 20)
kmeansvariation <- tibble("K" = 1:6,
                              "SS" = c(n_clusters_kmeans1$tot.withinss,
                                       n_clusters_kmeans2$tot.withinss,
                                       n_clusters_kmeans3$tot.withinss,
                                       n_clusters_kmeans4$tot.withinss,
                                       n_clusters_kmeans5$tot.withinss,
                                       n_clusters_kmeans6$tot.withinss))

ggplot(data = kmeansvariation, mapping = aes(x = K, y = SS)) +
  geom_line() +
  geom_point() +
  labs(title = "K means scree plot")

#complete linkage plot
n_pca_dist <- dist(n_pca)
distmatrix <- as.matrix(n_pca_dist)
n_clusters_hier<-hclust(dist(n_pca))
plot(n_clusters_hier, xlab = "", ylab = "", sub = "", 
     main = "Complete Linkage")

#cut = 4
n_clusters_hier_cut <- cutree(n_clusters_hier, 4)

n_pca_kmeans <- n_pca %>% mutate(cluster = n_clusters_kmeans4$cluster)
n_pca_hier <- n_pca %>% mutate(cluster = n_clusters_hier_cut)

ggplot(n_pca_kmeans, aes(x = PC1, y = PC2,
                          color = as.factor(cluster))) + 
  geom_point(alpha = .6) +
  labs(title = "kmeans clustering")

ggplot(n_pca_hier, aes(x = PC1, y = PC2, 
                        color = as.factor(cluster))) +
  geom_point(alpha = .6) +
  labs(title = "hierarchical clustering")
```

```{r}
n_pca_kmeans$album_name <- album_PCA_titles$album_name
n_pca_kmeans$artist <- album_PCA_titles$artist

n_pca_hier$album_name <- album_PCA_titles$album_name
n_pca_hier$artist <- album_PCA_titles$artist
```


```{r}
#saving data for dashboard
write_csv(pca_rotations, file = "pca_rotations.csv")
write_csv(pca_titles, file = "pca_titles.csv")
#n_clusters_hier <- as.data.frame(n_clusters_hier)
#write_csv(n_clusters_hier, file = "n_clusters_hier.csv")
write_csv(n_pca_kmeans, file = "n_pca_kmeans.csv")
write_csv(n_pca_hier, file = "n_pca_hier.csv")
```

